import java.awt.Color;
import java.sql.*;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Panel.java
 *
 * Created on 5 Feb, 2016, 4:47:54 PM
 */

/**
 *
 * @author DELL
 */
public class Panel extends javax.swing.JFrame {

    /** Creates new form Panel */
    public Panel() {
        initComponents();
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d1 = new javax.swing.JDialog();
        l15 = new javax.swing.JLabel();
        sp2 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        b9 = new javax.swing.JButton();
        f4 = new javax.swing.JFrame();
        sp3 = new javax.swing.JScrollPane();
        ta2 = new javax.swing.JTextArea();
        b11 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        f7 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        l33 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        l5 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        b4 = new javax.swing.JButton();
        r7 = new javax.swing.JRadioButton();
        cb3 = new javax.swing.JComboBox();
        r4 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        l100 = new javax.swing.JLabel();
        l101 = new javax.swing.JLabel();
        l102 = new javax.swing.JLabel();
        cb4 = new javax.swing.JComboBox();
        cb5 = new javax.swing.JComboBox();
        cb6 = new javax.swing.JComboBox();
        l103 = new javax.swing.JLabel();
        l104 = new javax.swing.JLabel();
        l105 = new javax.swing.JLabel();
        NewPayment = new javax.swing.JFrame();
        tp1 = new javax.swing.JTabbedPane();
        p2 = new javax.swing.JPanel();
        l39 = new javax.swing.JLabel();
        l40 = new javax.swing.JLabel();
        l41 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        l43 = new javax.swing.JLabel();
        l30 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        l34 = new javax.swing.JLabel();
        l35 = new javax.swing.JLabel();
        l36 = new javax.swing.JLabel();
        l37 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        cb2 = new javax.swing.JComboBox();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        l50 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        l42 = new javax.swing.JLabel();
        l44 = new javax.swing.JLabel();
        l45 = new javax.swing.JLabel();
        t12 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        l46 = new javax.swing.JLabel();
        l48 = new javax.swing.JLabel();
        l49 = new javax.swing.JLabel();
        t25 = new javax.swing.JTextField();
        t26 = new javax.swing.JTextField();
        l47 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg1 = new javax.swing.ButtonGroup();
        bg2 = new javax.swing.ButtonGroup();
        t3 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        sp1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        l29 = new javax.swing.JLabel();
        l32 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        d1.setMinimumSize(new java.awt.Dimension(410, 285));

        l15.setFont(new java.awt.Font("Poor Richard", 1, 36));
        l15.setForeground(new java.awt.Color(0, 0, 255));
        l15.setText("OFFERS!");

        ta.setBackground(new java.awt.Color(240, 240, 240));
        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Century Gothic", 0, 13));
        ta.setRows(5);
        ta.setText(" 1. 5% discount on shopping over Rs. 50000.\n 2. 7% discount on shopping over Rs. 200000.\n 3. 12% discount on using HDFC Bank Credit Card.\n 4. 12% discount on using SBI Bank Credit Card.\n 5. 15% discount on using ICICI Bank Credit Card.\n 6. 10% discount on using AXIS Bank Credit Card.");
        ta.setCaretColor(new java.awt.Color(240, 240, 240));
        sp2.setViewportView(ta);

        b9.setText("EXIT");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout d1Layout = new javax.swing.GroupLayout(d1.getContentPane());
        d1.getContentPane().setLayout(d1Layout);
        d1Layout.setHorizontalGroup(
            d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(d1Layout.createSequentialGroup()
                .addGroup(d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(d1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(b9))
                    .addGroup(d1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(sp2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(d1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(l15)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        d1Layout.setVerticalGroup(
            d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(d1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l15)
                .addGap(18, 18, 18)
                .addComponent(sp2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(b9)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        f4.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        f4.setMinimumSize(new java.awt.Dimension(450, 533));

        ta2.setColumns(20);
        ta2.setEditable(false);
        ta2.setFont(new java.awt.Font("Century Gothic", 1, 18));
        ta2.setRows(5);
        ta2.setMaximumSize(new java.awt.Dimension(700, 1200));
        ta2.setMinimumSize(new java.awt.Dimension(0, 0));
        sp3.setViewportView(ta2);

        b11.setText("Print");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b14.setText("New Customer Entry");
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b12.setText("Print Item List");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout f4Layout = new javax.swing.GroupLayout(f4.getContentPane());
        f4.getContentPane().setLayout(f4Layout);
        f4Layout.setHorizontalGroup(
            f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp3, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addGroup(f4Layout.createSequentialGroup()
                        .addComponent(b11)
                        .addGap(41, 41, 41)
                        .addComponent(b12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(b14)))
                .addContainerGap())
        );
        f4Layout.setVerticalGroup(
            f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp3, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b11)
                    .addComponent(b14)
                    .addComponent(b12))
                .addContainerGap())
        );

        f7.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        f7.setMinimumSize(new java.awt.Dimension(670, 685));

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Contact No.", "Payment Mode", "Total Amount", "Discount", "Net Amount", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tb2);
        tb2.getColumnModel().getColumn(0).setResizable(false);
        tb2.getColumnModel().getColumn(0).setPreferredWidth(125);
        tb2.getColumnModel().getColumn(1).setResizable(false);
        tb2.getColumnModel().getColumn(1).setPreferredWidth(125);
        tb2.getColumnModel().getColumn(2).setResizable(false);
        tb2.getColumnModel().getColumn(2).setPreferredWidth(200);
        tb2.getColumnModel().getColumn(3).setResizable(false);
        tb2.getColumnModel().getColumn(3).setPreferredWidth(125);
        tb2.getColumnModel().getColumn(4).setResizable(false);
        tb2.getColumnModel().getColumn(4).setPreferredWidth(125);
        tb2.getColumnModel().getColumn(5).setResizable(false);
        tb2.getColumnModel().getColumn(5).setPreferredWidth(125);
        tb2.getColumnModel().getColumn(6).setResizable(false);
        tb2.getColumnModel().getColumn(6).setPreferredWidth(150);

        l33.setFont(new java.awt.Font("Poor Richard", 0, 36));
        l33.setText("CUSTOMER LIST");

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        l5.setText("ORDER BY");

        l2.setText("SEARCH BY");

        b4.setText("SEARCH");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        bg1.add(r7);
        r7.setText("NONE");

        cb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ASC", "DESC" }));

        bg2.add(r4);
        r4.setText("NET AMOUNT");

        bg1.add(r2);
        r2.setText("NAME");

        bg2.add(r6);
        r6.setText("DATE");

        bg1.add(r3);
        r3.setText("DATE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r2))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r6)
                            .addComponent(r3))))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r7)
                            .addComponent(r3)
                            .addComponent(r2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r6)
                            .addComponent(r4)
                            .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l5)))))
        );

        jTabbedPane1.addTab("SEARCH", jPanel1);

        l100.setText("NO. OF PURCHASES");

        l101.setText("NO. OF CUSTOMERS");

        l102.setText("TOTAL SALES");

        cb4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "THIS MONTH", "SINCE BEGINNING", "THIS YEAR", "TODAY" }));
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });

        cb5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "THIS MONTH", "SINCE BEGINNING", "THIS YEAR", "TODAY" }));
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });

        cb6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "THIS MONTH", "SINCE BEGINNING", "THIS YEAR", "TODAY" }));
        cb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l101)
                    .addComponent(l102)
                    .addComponent(l100))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l103, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l104, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l105, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l100)
                    .addComponent(cb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l103, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l101)
                    .addComponent(cb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l104, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l102)
                    .addComponent(cb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l105, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("OVERVIEW", jPanel2);

        javax.swing.GroupLayout f7Layout = new javax.swing.GroupLayout(f7.getContentPane());
        f7.getContentPane().setLayout(f7Layout);
        f7Layout.setHorizontalGroup(
            f7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(f7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE))
                .addGap(32, 32, 32))
            .addGroup(f7Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(l33)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        f7Layout.setVerticalGroup(
            f7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l33, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        NewPayment.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        NewPayment.setMinimumSize(new java.awt.Dimension(540, 600));

        tp1.setMinimumSize(new java.awt.Dimension(84, 60));

        l39.setFont(new java.awt.Font("Berlin Sans FB", 0, 14));
        l39.setText("Amount");

        l40.setFont(new java.awt.Font("Berlin Sans FB", 0, 14));
        l40.setText("Discount");

        l41.setFont(new java.awt.Font("Berlin Sans FB", 0, 14));
        l41.setText("Payable Amount");

        t9.setEditable(false);

        t10.setEditable(false);
        t10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t10ActionPerformed(evt);
            }
        });

        t8.setEditable(false);

        l43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Viewbill.png"))); // NOI18N
        l43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l43MouseClicked(evt);
            }
        });

        l30.setText("Payment through Cash is not availabe for purchase over 2 Lakh.");

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l40, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(l39, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(l41))
                .addGap(42, 42, 42)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t9)
                    .addComponent(t10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(l43)
                .addGap(163, 163, 163))
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(l30)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(l30)
                .addGap(27, 27, 27)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(l39)
                        .addGap(18, 18, 18)
                        .addComponent(l40)
                        .addGap(18, 18, 18)
                        .addComponent(l41))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(l43)
                .addGap(57, 57, 57))
        );

        tp1.addTab("CASH", p2);

        l34.setText("Select Bank");

        l35.setText("Amount");

        l36.setText("You Save");

        l37.setText("Total Payable Amount");

        t5.setEditable(false);

        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HDFC Bank", "State Bank of India", "ICICI Bank", "AXIS Bank", "Mahindra Bank", "IDBI Bank", "Union Bank of India", "Syndicate Bank", "Punjab National Bank", "Canara Bank" }));
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        t6.setEditable(false);

        t7.setEditable(false);

        l50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Viewbill.png"))); // NOI18N
        l50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l50MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l34)
                    .addComponent(l35)
                    .addComponent(l36)
                    .addComponent(l37, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(t7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(l50)
                .addGap(158, 158, 158))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l35))
                .addGap(27, 27, 27)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l34)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l36)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(l50)
                .addGap(47, 47, 47))
        );

        tp1.addTab("CREDIT CARD", p1);

        l42.setFont(new java.awt.Font("Berlin Sans FB", 0, 14));
        l42.setText("Amount");

        l44.setFont(new java.awt.Font("Berlin Sans FB", 0, 14));
        l44.setText("Discount");

        l45.setFont(new java.awt.Font("Berlin Sans FB", 0, 14));
        l45.setText("Payable Amount");

        t12.setEditable(false);

        t13.setEditable(false);

        t11.setEditable(false);

        l46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Viewbill.png"))); // NOI18N
        l46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l46MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l42)
                            .addComponent(l44)
                            .addComponent(l45))
                        .addGap(109, 109, 109)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t12)
                            .addComponent(t13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(l46)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l42)
                    .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l44)
                    .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(l46)
                .addGap(58, 58, 58))
        );

        tp1.addTab("CHEQUE", p3);

        l48.setFont(new java.awt.Font("Berlin Sans FB", 0, 14));
        l48.setText("Name");

        l49.setFont(new java.awt.Font("Berlin Sans FB", 0, 14));
        l49.setText("Contact No.");

        t25.setToolTipText("Enter your name");
        t25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t25ActionPerformed(evt);
            }
        });

        t26.setToolTipText("Enter your mobile number");

        l47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/offers.png"))); // NOI18N
        l47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l47MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment.png"))); // NOI18N

        javax.swing.GroupLayout NewPaymentLayout = new javax.swing.GroupLayout(NewPayment.getContentPane());
        NewPayment.getContentPane().setLayout(NewPaymentLayout);
        NewPaymentLayout.setHorizontalGroup(
            NewPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewPaymentLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(NewPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(NewPaymentLayout.createSequentialGroup()
                        .addGroup(NewPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l48)
                            .addComponent(l49))
                        .addGap(107, 107, 107)
                        .addGroup(NewPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t26)
                            .addComponent(t25, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l47))
                    .addComponent(tp1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(NewPaymentLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        NewPaymentLayout.setVerticalGroup(
            NewPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(NewPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NewPaymentLayout.createSequentialGroup()
                        .addGroup(NewPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l48))
                        .addGap(18, 18, 18)
                        .addGroup(NewPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l49))
                        .addGap(33, 33, 33))
                    .addGroup(NewPaymentLayout.createSequentialGroup()
                        .addComponent(l47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(tp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(240, 240, 240));
        setMinimumSize(new java.awt.Dimension(753, 574));
        setResizable(false);
        getContentPane().setLayout(null);

        t3.setToolTipText("Enter the quantity of product you want to purchase");
        getContentPane().add(t3);
        t3.setBounds(570, 150, 140, 20);

        l3.setFont(new java.awt.Font("Narkisim", 0, 15));
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("Item");
        getContentPane().add(l3);
        l3.setBounds(40, 110, 27, 15);

        l4.setFont(new java.awt.Font("Narkisim", 0, 15));
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setText("Quantity");
        getContentPane().add(l4);
        l4.setBounds(40, 150, 52, 15);

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Moto X STYLE", "Moto X PLAY", "Moto 360", "YU Yuphoria", "iPhone 6S", "Apple Macbook Pro", "Microsoft Surface Pro 4", "Samsung NX300", "Sennheiser RS 120", "WD My Passport Ultra", "Sandisk Cruzer Force", "Sony Bravia X4", "Cannon IXUS 140", "Sony HT-M55 System", "Xbox 360 4GB Console", "Strontium 16GB MicroSD", "Nikon D3200 DSLR", "HP DeskJet 1010 Printer", "JBL Pulse", "Alienware 17" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(570, 110, 141, 20);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No.", "Item", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb1.setOpaque(false);
        sp1.setViewportView(tb1);

        getContentPane().add(sp1);
        sp1.setBounds(40, 230, 670, 200);

        b1.setText("ADD");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(650, 190, 60, 23);

        b2.setText("REMOVE SELECTED ITEM(S)");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(40, 190, 167, 23);

        t4.setEditable(false);
        getContentPane().add(t4);
        t4.setBounds(570, 450, 140, 20);

        l29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continue.png"))); // NOI18N
        l29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l29MouseClicked(evt);
            }
        });
        getContentPane().add(l29);
        l29.setBounds(300, 480, 130, 50);

        l32.setFont(new java.awt.Font("Narkisim", 0, 15));
        l32.setForeground(new java.awt.Color(255, 255, 255));
        l32.setText("Total");
        getContentPane().add(l32);
        l32.setBounds(40, 450, 29, 15);

        b3.setText("CUSTOMER LIST");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(40, 490, 111, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 550);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laptop.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 90, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/headphone.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 70, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
String q = "Short";
try
{Short.parseShort(t3.getText());}
catch (NumberFormatException e)
{q = "Not Short";}

if (q=="Not Short" && t3.getText().length()!=0)
{JOptionPane.showMessageDialog(this,"Please Enter a Natural Number");
t3.setText("");}

else if (t3.getText().equals(""))
{JOptionPane.showMessageDialog(this,"Please Enter Quantity");}

else if (q=="Short")
{int y = Integer.parseInt(t3.getText());
if (y==0)
{JOptionPane.showMessageDialog(this,"Please Enter a Natural Number");}
else if (y!=0)
{String a = (String)cb1.getSelectedItem();
int x = cb1.getSelectedIndex();

double b = 0;

{if (x==0)
    b = 26999;
else if (x==1)
    b = 16999;
else if (x==2)
    b = 17999;
else if (x==3)
    b = 6999;
else if (x==4)
    b = 57790;
else if (x==5)
    b = 78900;
else if (x==6)
    b = 89990;
else if (x==7)
    b = 50285;
else if (x==8)
    b = 7299;
else if (x==9)
    b = 4099;
else if (x==10)
    b = 399;
else if (x==11)
    b = 69900;
else if (x==12)
    b = 8399;
else if (x==13)
    b = 47190;
else if (x==14)
    b = 12490;
else if (x==15)
    b = 299;
else if (x==16)
    b = 20999;
else if (x==17)
    b = 1849;
else if (x==18)
    b = 8999;
else if (x==19)
    b = 186890;}

double z = b*y;
int rc = tb1.getRowCount();
int c = rc+1;

Object[] items = {" "+c," "+a," "+b," "+y," "+z};
DefaultTableModel tm = (DefaultTableModel)tb1.getModel();
tm.addRow(items);

double sum = 0;
int rc2 = tb1.getRowCount();

{for (int i = 0; i<rc2; i++)
{sum = sum+Double.parseDouble(tb1.getValueAt(i, 4).toString());}
t4.setText(""+sum);}}}


}//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
if (tb1.getRowCount()==0)
{JOptionPane.showMessageDialog(this, "Table is Empty");}

else if (tb1.getRowCount()>0)
{if (tb1.getSelectedRow()==-1)
{JOptionPane.showMessageDialog(this, "No Row Selected");}

else {
int[] rows = tb1.getSelectedRows();
DefaultTableModel tm = (DefaultTableModel)tb1.getModel();

for (int i=0;i<rows.length;i++)
{tm.removeRow(rows[i]-i);}

for (int i=0;i<tb1.getRowCount();i++)
{    tb1.setValueAt((i+1), i, 0);}

double sum = 0;
int rc2 = tb1.getRowCount();

for (int i = 0; i<rc2; i++)
{sum = sum+Double.parseDouble(tb1.getValueAt(i, 4).toString());}
t4.setText(""+sum);}}
// TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
d1.dispose();        // TODO add your handling code here:
}//GEN-LAST:event_b9ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        try {
            ta2.print(); // TODO add your handling code here:
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(this, "Error in Printing");
        }
}//GEN-LAST:event_b11ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
ta2.setText("");
t6.setText("");
t7.setText("");
t25.setText("");
t26.setText("");
t3.setText("");
t4.setText("");

this.setVisible(true);
f4.setVisible(false);
NewPayment.dispose();

int rc = tb1.getRowCount();
DefaultTableModel tm = (DefaultTableModel)tb1.getModel();
for (int i=0 ; i<rc ; i++)
{tm.removeRow(0);}
// TODO add your handling code here:
    }//GEN-LAST:event_b14ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        try {
            tb1.print(); // TODO add your handling code here:
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(this, "Error in Printing");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_b12ActionPerformed

    private void l29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l29MouseClicked
if (t4.getText().equals(""))
{JOptionPane.showMessageDialog(this,"Please Select atleast One Product");}

else if (Double.parseDouble(t4.getText())==0.0)
{JOptionPane.showMessageDialog(this,"Please Select atleast One Product");}


else {
    float k = 200000;
float p = 50000;
float dis = 0;
float total = Float.parseFloat(t4.getText());

if (total>=k)
{dis = total*7/100;}
else if (total>p && total<k)
{dis = total*5/10;}
NewPayment.setVisible(true);
t5.setText(""+total);
t11.setText(""+total);
t12.setText(""+dis);
t13.setText(""+(total-dis));
if (total>k)
{p2.setVisible(false);
 l39.setVisible(false);
 l40.setVisible(false);
 l41.setVisible(false);
 t9.setVisible(false);
 t10.setVisible(false);
 t8.setVisible(false);
 l43.setVisible(false);
 l30.setVisible(true);
 }
else
{
    p2.setVisible(true);
 l39.setVisible(true);
 l40.setVisible(true);
 l41.setVisible(true);
 t9.setVisible(true);
 t10.setVisible(true);
 t8.setVisible(true);
 l43.setVisible(true);
 l30.setVisible(false);
 t8.setText(""+total);
t9.setText(""+dis);
t10.setText(""+(total-dis));}



}
        // TODO add your handling code here:
}//GEN-LAST:event_l29MouseClicked

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
// Connectivity
        int rc2 = tb2.getRowCount();
        DefaultTableModel tm2 = (DefaultTableModel)tb2.getModel();
        for (int i=0 ; i<rc2 ; i++)
        {tm2.removeRow(0);}

        f7.setVisible(true);
        
        try {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Electronics","root","system");
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("select * from Customers;");
        while (rs.next()){
        String d1 = rs.getString("Name");
        String d2 = rs.getString("Contact_No");
        String d3 = rs.getString("Payment_Mode");
        String d4 = rs.getString("Total_Amount");
        String d5 = rs.getString("Discount");
        String d6 = rs.getString("Net_Amount");
        String d7 = rs.getString("Date");
        String d8 = rs.getString("Time");

        Object[] row = {""+d1,""+d2,""+d3,""+d4,""+d5,""+d6,""+d7,""+d8};
        tm2.addRow(row);}
        rs.close();
        st.close();
        conn.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Error in Connectivity");
        }

        try {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Electronics","root","system");
        Statement st = conn.createStatement();
        ResultSet rs2 = st.executeQuery("select COUNT(NAME) from Customers WHERE MONTH(DATE)=MONTH(CURDATE()) AND YEAR(DATE)=YEAR(CURDATE());");
        while (rs2.next()){
        String nop = rs2.getString("COUNT(NAME)");
        l103.setText(""+nop);}

        ResultSet rs3 = st.executeQuery("select COUNT(DISTINCT CONTACT_NO) from Customers WHERE MONTH(DATE)=MONTH(CURDATE()) AND YEAR(DATE)=YEAR(CURDATE());");
        while (rs3.next()){
        String noc = rs3.getString("COUNT(DISTINCT CONTACT_NO)");
        l104.setText(""+noc);}

        ResultSet rs4 = st.executeQuery("select SUM(NET_AMOUNT) from Customers WHERE MONTH(DATE)=MONTH(CURDATE()) AND YEAR(DATE)=YEAR(CURDATE());");
        while (rs4.next()){
        String ts = rs4.getString("SUM(NET_AMOUNT)");
        l105.setText("Rs. "+ts);}
        
        rs2.close();
        rs3.close();
        rs4.close();
        st.close();
        conn.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Error in Connectivity");
        }



// Connectivity
    }//GEN-LAST:event_b3ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        double sum = Double.parseDouble(t4.getText());
        int h = (Integer)cb2.getSelectedIndex();
        double dis = 0;
        if (h==0)
            dis = sum*12/100;
        else if (h==1)
            dis = sum*12/100;
        else if (h==2)
            dis = sum*15/100;
        else if (h==3)
            dis = sum*10/100;
        else if (h==3||h==4||h==5||h==6||h==7||h==8||h==9) {
            if (sum>=50000 && sum<200000)
                dis = sum*5/100;
            else if (sum>=200000)
                dis = sum*7/100;
        }
        t6.setText(""+dis);
        t7.setText(""+(sum-dis));        // TODO add your handling code here:
}//GEN-LAST:event_cb2ActionPerformed

    private void l43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l43MouseClicked
{String q = "Long";
try
{Long.parseLong(t26.getText());}
catch(NumberFormatException ex)
{q = "Not Long" ;}

if (t25.getText().equals(""))
{JOptionPane.showMessageDialog(this,"Please Enter your Name");}

if (q=="Not Long" || t26.getText().length()!=10)
{JOptionPane.showMessageDialog(this,"Please Enter a Valid Phone Number");
t26.setText("");}

else if (t25.getText().length()>0)
{
    this.setVisible(false);
    f4.setVisible(true);
ta2.setText("");
Date date = new Date();
SimpleDateFormat dt = new SimpleDateFormat ("dd-MM-yyyy");
SimpleDateFormat tt = new SimpleDateFormat ("hh:mm  a");
ta2.append(" ");
ta2.append("\n   TECH WORLD"+"\n "+"  PLOT-101, NEW MARKET, BHOPAL");
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   DATE :-  "+dt.format(date));
ta2.append("\n   TIME  :-  "+tt.format(date));
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   "+"CUSTOMER NAME :-  "+t25.getText());
ta2.append("\n   "+"CONTACT NO. :-  "+t26.getText());
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   "+"PAYMENT MODE :- "+"Cash");
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   "+"TOTAL :- Rs. "+t4.getText());
{ta2.append("\n   "+"DISCOUNT :- Rs. "+t9.getText());
 ta2.append("\n   "+"NET TOTAL :- Rs. "+t10.getText());}
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   "+"            THANK YOU AND VISIT AGAIN");

String p = t25.getText();
String w = t26.getText();
String e = "Cash";
String r = t4.getText();
String t = t9.getText();
String y = t10.getText();
SimpleDateFormat dt2 = new SimpleDateFormat ("yyyy-MM-dd");
String u = dt2.format(date);
SimpleDateFormat tt2 = new SimpleDateFormat ("hh:mm:ss");
String i = tt2.format(date);

try {
    Class.forName("java.sql.Driver");
    Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/Electronics","root","system");
    Statement stmt = (Statement) conn.createStatement();
    String query ="insert into Customers values('"+p+"','"+w+"','"+e+"',"+r+","+t+","+y+",'"+u+"','"+i+"');";
    stmt.executeUpdate(query);
}
catch (Exception ex)
{JOptionPane.showMessageDialog(this, "Error In Connectivity");}
} }
// TODO add your handling code here:
}//GEN-LAST:event_l43MouseClicked

    private void l46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l46MouseClicked

{String q = "Long";
try
{Long.parseLong(t26.getText());}
catch(NumberFormatException ex)
{q = "Not Long" ;}

if (t25.getText().equals(""))
{JOptionPane.showMessageDialog(this,"Please Enter your Name");}

if (q=="Not Long" || t26.getText().length()!=10)
{JOptionPane.showMessageDialog(this,"Please Enter a Valid Phone Number");
t26.setText("");}

else if (t25.getText().length()>0)
{
    this.setVisible(false);
    f4.setVisible(true);
ta2.setText("");
Date date = new Date();
SimpleDateFormat dt = new SimpleDateFormat ("dd-MM-yyyy");
SimpleDateFormat tt = new SimpleDateFormat ("hh:mm  a");
ta2.append(" ");
ta2.append("\n   TECH WORLD"+"\n "+"  PLOT-101, NEW MARKET, BHOPAL");
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   DATE :-  "+dt.format(date));
ta2.append("\n   TIME  :-  "+tt.format(date));
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   "+"CUSTOMER NAME :-  "+t25.getText());
ta2.append("\n   "+"CONTACT NO. :-  "+t26.getText());
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   "+"PAYMENT MODE :- "+"Cheque");
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   "+"TOTAL :- Rs. "+t4.getText());
{ta2.append("\n   "+"DISCOUNT :- Rs. "+t12.getText());
 ta2.append("\n   "+"NET TOTAL :- Rs. "+t13.getText());}
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   "+"            THANK YOU AND VISIT AGAIN");

String p = t25.getText();
String w = t26.getText();
String e = "Cheque";
String r = t4.getText();
String t = t12.getText();
String y = t13.getText();
SimpleDateFormat dt2 = new SimpleDateFormat ("yyyy-MM-dd");
String u = dt2.format(date);
SimpleDateFormat tt2 = new SimpleDateFormat ("hh:mm:ss");
String i = tt2.format(date);

try {
    Class.forName("java.sql.Driver");
    Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/Electronics","root","system");
    Statement stmt = (Statement) conn.createStatement();
    String query ="insert into Customers values('"+p+"','"+w+"','"+e+"',"+r+","+t+","+y+",'"+u+"','"+i+"');";
    stmt.executeUpdate(query);
}
catch (Exception ex)
{JOptionPane.showMessageDialog(this, "Error In Connectivity");}}}

// TODO add your handling code here:
}//GEN-LAST:event_l46MouseClicked

    private void l47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l47MouseClicked
        d1.setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_l47MouseClicked

    private void t10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t10ActionPerformed

    private void t25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t25ActionPerformed

private void l50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l50MouseClicked
if (t6.getText().equals(""))
{JOptionPane.showMessageDialog(this,"Please Select A Bank");}

else
{String q = "Long";
try
{Long.parseLong(t26.getText());}
catch(NumberFormatException ex)
{q = "Not Long" ;}

if (t25.getText().equals(""))
{JOptionPane.showMessageDialog(this,"Please Enter your Name");}

if (q=="Not Long" || t26.getText().length()!=10)
{JOptionPane.showMessageDialog(this,"Please Enter a Valid Phone Number");
t26.setText("");}

else if (t25.getText().length()>0)
{
    this.setVisible(false);
    f4.setVisible(true);
ta2.setText("");
Date date = new Date();
SimpleDateFormat dt = new SimpleDateFormat ("dd-MM-yyyy");
SimpleDateFormat tt = new SimpleDateFormat ("hh:mm  a");
ta2.append(" ");
ta2.append("\n   TECH WORLD"+"\n "+"  PLOT-101, NEW MARKET, BHOPAL");
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   DATE :-  "+dt.format(date));
ta2.append("\n   TIME  :-  "+tt.format(date));
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   "+"CUSTOMER NAME :-  "+t25.getText());
ta2.append("\n   "+"CONTACT NO. :-  "+t26.getText());
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   "+"PAYMENT MODE :- "+"Credit Card");
ta2.append("\n   "+"BANK :- "+cb2.getSelectedItem());
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   "+"TOTAL :- Rs. "+t4.getText());
{ta2.append("\n   "+"DISCOUNT :- Rs. "+t6.getText());
 ta2.append("\n   "+"NET TOTAL :- Rs. "+t7.getText());}
ta2.append("\n   "+"------------------------------------------------");
ta2.append("\n   "+"            THANK YOU AND VISIT AGAIN");

String p = t25.getText();
String w = t26.getText();
String e = "Credit Card - " + cb2.getSelectedItem();
String r = t4.getText();
String t = t6.getText();
String y = t7.getText();
SimpleDateFormat dt2 = new SimpleDateFormat ("yyyy-MM-dd");
String u = dt2.format(date);
SimpleDateFormat tt2 = new SimpleDateFormat ("hh:mm:ss");
String i = tt2.format(date);

try {
    Class.forName("java.sql.Driver");
    Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/Electronics","root","system");
    Statement stmt = (Statement) conn.createStatement();
    String query ="insert into Customers values('"+p+"','"+w+"','"+e+"',"+r+","+t+","+y+",'"+u+"','"+i+"');";
    stmt.executeUpdate(query);
}
catch (Exception ex)
{JOptionPane.showMessageDialog(this, "Error In Connectivity");}}}
// TODO add your handling code here:
}//GEN-LAST:event_l50MouseClicked

private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_t1ActionPerformed

private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
    DefaultTableModel tm2 = (DefaultTableModel)tb2.getModel();
    int rc = tb2.getRowCount();
    for (int i=0 ; i<rc ; i++) {
        tm2.removeRow(0);}

    try {
        Class.forName("java.sql.Driver");
        Connection conn2 = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Electronics","root","system");

        String Query = "";
        String text = t1.getText();

        Statement st = conn2.createStatement();


        
        if (r2.isSelected()) {
            if (r4.isSelected()) {
                Query = "Select * from Customers where Name like '%"+text+"%' order by Net_Amount "+cb3.getSelectedItem()+";";}
            else if (r6.isSelected()) {
                        Query = "Select * from Customers where Name like '%"+text+"%' order by Date "+cb3.getSelectedItem()+";";}
        } else if (r3.isSelected()) {
            if (r4.isSelected()) {
                Query = "Select * from Customers where Date like '"+text+"' order by Net_Amount "+cb3.getSelectedItem()+";";}
            else if (r6.isSelected()) {
                        Query = "Select * from Customers where Date like '"+text+"' order by Time "+cb3.getSelectedItem()+";";}
        }
        else if (r7.isSelected()) {
            if (r4.isSelected()) {
                Query = "Select * from Customers order by Net_Amount "+cb3.getSelectedItem()+";";}
            else if (r6.isSelected()) {
                        Query = "Select * from Customers order by Date "+cb3.getSelectedItem()+";";}
        }

        ResultSet rs = st.executeQuery(Query);
        while (rs.next()){
        String d1 = rs.getString("Name");
        String d2 = rs.getString("Contact_No");
        String d3 = rs.getString("Payment_Mode");
        String d4 = rs.getString("Total_Amount");
        String d5 = rs.getString("Discount");
        String d6 = rs.getString("Net_Amount");
        String d7 = rs.getString("Date");
        String d8 = rs.getString("Time");

        Object[] row = {""+d1,""+d2,""+d3,""+d4,""+d5,""+d6,""+d7,""+d8};
        tm2.addRow(row);}
        rs.close();
        st.close();
        conn2.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Error in Connectivity");
        }       // TODO add your handling code here:
}//GEN-LAST:event_b4ActionPerformed

private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
try {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Electronics","root","system");
        Statement st = conn.createStatement();
        ResultSet rs2 = st.executeQuery("select COUNT(NAME) from Customers WHERE MONTH(DATE)=MONTH(CURDATE()) AND YEAR(DATE)=YEAR(CURDATE());");
        if (cb4.getSelectedIndex()==1)
        {rs2 = st.executeQuery("select COUNT(NAME) from Customers;");}
        else if (cb4.getSelectedIndex()==2)
        {rs2 = st.executeQuery("select COUNT(NAME) from Customers WHERE YEAR(DATE)=YEAR(CURDATE());");}
        else if (cb4.getSelectedIndex()==3)
        {rs2 = st.executeQuery("select COUNT(NAME) from Customers WHERE DATE=CURDATE();");}
        while (rs2.next()){
        String nop = rs2.getString("COUNT(NAME)");
        l103.setText(""+nop);

        }
        rs2.close();
        st.close();
        conn.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Error in Connectivity");
        }    // TODO add your handling code here:
}//GEN-LAST:event_cb4ActionPerformed

private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
try {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Electronics","root","system");
        Statement st = conn.createStatement();
        ResultSet rs3 = st.executeQuery("select COUNT(DISTINCT CONTACT_NO) from Customers WHERE MONTH(DATE)=MONTH(CURDATE()) AND YEAR(DATE)=YEAR(CURDATE());");
        if (cb5.getSelectedIndex()==1)
        {rs3 = st.executeQuery("select COUNT(DISTINCT CONTACT_NO) from Customers;");}
        else if (cb5.getSelectedIndex()==2)
        {rs3 = st.executeQuery("select COUNT(DISTINCT CONTACT_NO) from Customers WHERE YEAR(DATE)=YEAR(CURDATE());");}
        else if (cb5.getSelectedIndex()==3)
        {rs3 = st.executeQuery("select COUNT(DISTINCT CONTACT_NO) from Customers WHERE DATE=CURDATE();");}
        while (rs3.next()){
        String noc = rs3.getString("COUNT(DISTINCT CONTACT_NO)");
        l104.setText(""+noc);

        }
        rs3.close();
        st.close();
        conn.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Error in Connectivity");
        }    // TODO add your handling code here:
}//GEN-LAST:event_cb5ActionPerformed

private void cb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb6ActionPerformed
try {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Electronics","root","system");
        Statement st = conn.createStatement();
        ResultSet rs4 = st.executeQuery("select SUM(NET_AMOUNT) from Customers WHERE MONTH(DATE)=MONTH(CURDATE()) AND YEAR(DATE)=YEAR(CURDATE());");
        if (cb6.getSelectedIndex()==1)
        {rs4 = st.executeQuery("select SUM(NET_AMOUNT) from Customers;");}
        else if (cb6.getSelectedIndex()==2)
        {rs4 = st.executeQuery("select SUM(NET_AMOUNT) from Customers WHERE YEAR(DATE)=YEAR(CURDATE());");}
        else if (cb6.getSelectedIndex()==3)
        {rs4 = st.executeQuery("select SUM(NET_AMOUNT) from Customers WHERE DATE=CURDATE();");}
        while (rs4.next()){
        String ts = rs4.getString("SUM(NET_AMOUNT)");
        l105.setText("Rs. "+ts);

        }
        rs4.close();
        st.close();
        conn.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Error in Connectivity");
        }    // TODO add your handling code here:
}//GEN-LAST:event_cb6ActionPerformed

private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_cb1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {


                try {
                     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
            if ("Windows".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;}
                     }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
                }
                

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Panel().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame NewPayment;
    private javax.swing.JButton b1;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b14;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b9;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.ButtonGroup bg2;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JComboBox cb4;
    private javax.swing.JComboBox cb5;
    private javax.swing.JComboBox cb6;
    private javax.swing.JDialog d1;
    private javax.swing.JFrame f4;
    private javax.swing.JFrame f7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel l100;
    private javax.swing.JLabel l101;
    private javax.swing.JLabel l102;
    private javax.swing.JLabel l103;
    private javax.swing.JLabel l104;
    private javax.swing.JLabel l105;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l29;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l30;
    private javax.swing.JLabel l32;
    private javax.swing.JLabel l33;
    private javax.swing.JLabel l34;
    private javax.swing.JLabel l35;
    private javax.swing.JLabel l36;
    private javax.swing.JLabel l37;
    private javax.swing.JLabel l39;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l40;
    private javax.swing.JLabel l41;
    private javax.swing.JLabel l42;
    private javax.swing.JLabel l43;
    private javax.swing.JLabel l44;
    private javax.swing.JLabel l45;
    private javax.swing.JLabel l46;
    private javax.swing.JLabel l47;
    private javax.swing.JLabel l48;
    private javax.swing.JLabel l49;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l50;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JScrollPane sp1;
    private javax.swing.JScrollPane sp2;
    private javax.swing.JScrollPane sp3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t25;
    private javax.swing.JTextField t26;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextArea ta2;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    private javax.swing.JTabbedPane tp1;
    // End of variables declaration//GEN-END:variables

}
